volumes:
    n8n_data:

services:
    tunnel:
        image: cloudflare/cloudflared:2023.8.1
        container_name: tunnel
        command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
        restart: always

    uptime:
        image: louislam/uptime-kuma:1.23.0-alpine
        container_name: uptime
        restart: always
        volumes:
            - ./uptime:/app/data

    database:
        image: mariadb:10.6
        container_name: database
        environment:
            MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
        ports:
            - 3306:3306
        restart: always
        volumes:
            - ./database:/var/lib/mysql

    database-pg:
        image: ghcr.io/marvinisaac/postgres-backup/postgres-backup:0.4.0
        container_name: database-pg
        environment:
            POSTGRES_PASSWORD: ${DATABASE_PG_ROOT_PASSWORD}
        ports:
            - 5432:5432
        restart: always
        volumes:
            - ./database-pg:/var/lib/postgresql/database
