volumes:
    n8n_data:

services:
    tunnel:
        image: cloudflare/cloudflared:2023.8.1
        container_name: tunnel
        command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
        restart: always

    uptime:
        image: louislam/uptime-kuma:1.23.0-alpine
        container_name: uptime
        restart: always
        volumes:
            - ./uptime:/app/data
    
    n8n:
        image: docker.n8n.io/n8nio/n8n:1.64.3
        container_name: n8n
        environment:
            DB_POSTGRESDB_HOST: "database-pg"
            DB_POSTGRESDB_PASSWORD: ${DATABASE_PG_ROOT_PASSWORD}
            GENERIC_TIMEZONE: "Asia/Manila"
            N8N_HOST: "automation.marvinisaac.com"
            N8N_PORT: 80
            NODE_ENV: production
            N8N_LOG_LEVEL: debug
            N8N_DIAGNOSTICS_ENABLED: false
        ports:
            - 80:80
        restart: always
        volumes:
            - n8n_data:/home/node/.n8n

    database:
        image: mariadb:10.6
        container_name: database
        environment:
            MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
        ports:
            - 3306:3306
        restart: always
        volumes:
            - ./database:/var/lib/mysql

    database-pg:
        image: ghcr.io/marvinisaac/postgres-backup/postgres-backup:0.4.0
        container_name: database-pg
        environment:
            POSTGRES_PASSWORD: ${DATABASE_PG_ROOT_PASSWORD}
        ports:
            - 5432:5432
        restart: always
        volumes:
            - ./database-pg:/var/lib/postgresql/database
