services:
    tunnel:
        image: cloudflare/cloudflared:2023.8.1
        container_name: tunnel
        command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
        restart: always

    uptime:
        image: louislam/uptime-kuma:1.23.0-alpine
        container_name: uptime
        restart: always
        volumes:
            - ./uptime:/app/data
