services:
    tunnel:
        image: cloudflare/cloudflared:2023.8.1
        container_name: tunnel
        command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
        restart: always

    uptime:
        image: louislam/uptime-kuma:1.23.0-alpine
        restart: always
        volumes:
            - ./uptime:/app/data

    shlink:
        image: shlinkio/shlink:stable
        environment:
            - DEFAULT_DOMAIN=qckbt.cc
            - IS_HTTPS_ENABLED=true
            - GEOLITE_LICENSE_KEY=${SHLINK_GEOLITE_KEY}
            - INITIAL_API_KEY=${SHLINK_API_KEY}
        ports:
            - 8080:8080
        restart: always
